language: node_js
env:
  global:
    - secure: "hfWlEytynudODv9mj7kNApvcXFZK3KYO7BoAYIIf+OJGmDcwWcY9zClGV47mXHXLwkvO8YOATWX+RSm5WL7+Z9hH9hMUW0A5tpX7POxXknEJfQzu7u/FG3tYVWWuPvzPjCO78r3MyDPonYAP752p3qskZf67w4KMzTSFIu/W7o51yzRGJNJhQ7+L+M9Ez0NRVdrmj3A+HD+mEaMCgu0HHY3JD7JyqoMXFCaeQVcUJpjBEFs92R5YCD2MKROtdS9S2Dv6xD6XSGyNTlTvtQPb74xAWljyY2m4huVquc9+eyZ1LN5ggLAoPfF8e3kHpEaKndtElk8IPg+NzZap6maF+HKkbs1BpUKCKKOfdsO4gcZkIAwa5+ZsAd3g5UvPoAiERrjw7cG3z5SaJQTyynSWypMCbIHqpK91AicS/LizRGAl6rO7i8uSS5QFTJVoh9+gGYnZspMJyrAVN9E1e0C3pKQdn7H4vH1jTboqE0aujLJZlgMgF5WSV2zuFlDnRldGgdUlm8LR8eIbo3O2CGr8unNFPKHrNrx19/g5kG1b1X+esMRx60WFevNXUhpLxXGzxE5wWkguIsPPwLu7Ia8CmEHlMbObmw2NzpY8lE9cnTRN2ROzYwZttogEvav/+GbN6RUDSwP6JDQCtvwd/70lUAppGHxmwL2AkPtrIeqvxgI="
    - secure: "EpgXObCoSeLHq10YGK8VyxHDao0trMC4lH1UfkK7vbxCfI+v3O3TEEKeLaw0XZF5Egr7cR3QpalmcaDC/EFwpYqMplFOFmZ53hbacSan800+xV6IWmJ15jkVQ7ILjgzFgSymkDkKj+eabMXyb9zofL3xUDU9SEav8k/7J5jPop1T/7DlEuyHBUbJrkY3OlNy2NkUmn4v2uSC2KB079MgE9XilD0khFzn8Uoe4mhuIjVEt4caF0WLDdVilyDeTymgKQNKETivLJ+cswwo6+arq9J+p7Tx3JZfzP0gOG0wZFgAKcMsc2fVeqj3klbXY1geLyG/UT0uyW2Ded2vXMbw/FJVBIOHS3AB+eGIjgG0RcxX8uVjkGrryWtZaP4hAPG4YCnp5/WWGXJ7A6g/3NdNWRKdKi+ME0AN9v4kVQXg9kxCUBgF01C/RUH1+ADNPBZtewBAgC7crzetwvRwXzIu2v7bekQSGUAyzhTf8FhJF+o0lAIw9dEuiWf8uBZpplISwXj1Sy7dTCnHKqtIsY+LzocMzo83RMDZ2EwxhrQUzvNdLIn0eO3pNXG7L26ymdLvPyHYcR4YGqnnTN3A/ZautfY2XZYnz7fqR0PhsH61SiejLvSxMrx8Tp1CLd0lqYz+wvUy0b1SxaqCqu1eJrEZa8J17RyEEnGU5l/X40movm0="
before_install:
 - sudo snap install jo
install:
 - npm install
script:
 - npm run build
node_js:
- node
after_success:
 - bash travis_build.sh